### ISSUE TITLE
`from_ir` does not seem to support input parameters

### ISSUE THREAD

**Issue by rchilaka-amzn** [aws/amazon-braket-sdk-python#632]
**Describe the bug**
Unable to create `Circuit` class using `from_ir` when the source program contains parameters

**To reproduce**
```
from braket.circuits import Circuit

parametric_source = "OPENQASM 3.0; input angle alpha; qubit[2] q; bit[2] c; rx(alpha*2) q[0]; rz(alpha) q[1]; c = measure q;"
Circuit.from_ir(parametric_source, inputs={"alpha": 0.1})
```

**Expected behavior**
I expect to get back an instance of the `Circuit` object like when the source does not contain an input parameter

**Screenshots or logs**
Error when I try the program above:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Caskroom/miniconda/base/envs/Braket/lib/python3.10/site-packages/braket/circuits/circuit.py", line 1148, in from_ir
    return Interpreter(BraketProgramContext()).build_circuit(
  File "/usr/local/Caskroom/miniconda/base/envs/Braket/lib/python3.10/site-packages/braket/default_simulator/openqasm/interpreter.py", line 135, in build_circuit
    self.visit(program)
  File "/usr/local/Caskroom/miniconda/base/envs/Braket/lib/python3.10/functools.py", line 926, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/Braket/lib/python3.10/site-packages/braket/default_simulator/openqasm/interpreter.py", line 169, in _
    self.visit(node.statements)
  File "/usr/local/Caskroom/miniconda/base/envs/Braket/lib/python3.10/functools.py", line 926, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/Braket/lib/python3.10/site-packages/braket/default_simulator/openqasm/interpreter.py", line 165, in _
    return [n for n in [self.visit(node) for node in node_list] if n is not None]
  File "/usr/local/Caskroom/miniconda/base/envs/Braket/lib/python3.10/site-packages/braket/default_simulator/openqasm/interpreter.py", line 165, in <listcomp>
    return [n for n in [self.visit(node) for node in node_list] if n is not None]
  File "/usr/local/Caskroom/miniconda/base/envs/Braket/lib/python3.10/functools.py", line 926, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/Braket/lib/python3.10/site-packages/braket/default_simulator/openqasm/interpreter.py", line 194, in _
    self.visit(declaration)
  File "/usr/local/Caskroom/miniconda/base/envs/Braket/lib/python3.10/functools.py", line 926, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/Braket/lib/python3.10/site-packages/braket/default_simulator/openqasm/interpreter.py", line 176, in _
    init_value = cast_to(node.type, init_expression)
  File "/usr/local/Caskroom/miniconda/base/envs/Braket/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/Caskroom/miniconda/base/envs/Braket/lib/python3.10/site-packages/braket/default_simulator/openqasm/_helpers/casting.py", line 41, in cast_to
    raise TypeError(f"Cannot cast {type(variable).__name__} into {into.__name__}.")
AttributeError: 'AngleType' object has no attribute '__name__'. Did you mean: '__ne__'?
```

When I try to skip providing a value for the input parameter, I see a different error:
```
Circuit.from_ir(parametric_source)
```

Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Caskroom/miniconda/base/envs/Braket/lib/python3.10/site-packages/braket/circuits/circuit.py", line 1148, in from_ir
    return Interpreter(BraketProgramContext()).build_circuit(
  File "/usr/local/Caskroom/miniconda/base/envs/Braket/lib/python3.10/site-packages/braket/default_simulator/openqasm/interpreter.py", line 135, in build_circuit
    self.visit(program)
  File "/usr/local/Caskroom/miniconda/base/envs/Braket/lib/python3.10/functools.py", line 926, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/Braket/lib/python3.10/site-packages/braket/default_simulator/openqasm/interpreter.py", line 169, in _
    self.visit(node.statements)
  File "/usr/local/Caskroom/miniconda/base/envs/Braket/lib/python3.10/functools.py", line 926, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/Braket/lib/python3.10/site-packages/braket/default_simulator/openqasm/interpreter.py", line 165, in _
    return [n for n in [self.visit(node) for node in node_list] if n is not None]
  File "/usr/local/Caskroom/miniconda/base/envs/Braket/lib/python3.10/site-packages/braket/default_simulator/openqasm/interpreter.py", line 165, in <listcomp>
    return [n for n in [self.visit(node) for node in node_list] if n is not None]
  File "/usr/local/Caskroom/miniconda/base/envs/Braket/lib/python3.10/functools.py", line 926, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/Braket/lib/python3.10/site-packages/braket/default_simulator/openqasm/interpreter.py", line 191, in _
    raise NameError(f"Missing input variable '{node.identifier.name}'.")
NameError: Missing input variable 'alpha'.
```

**System information**
A description of your system. Please provide:
- **Amazon Braket Python SDK version**: 1.49.1
- **Amazon Braket Python Schemas version**: 1.19.0
- **Amazon Braket Python Default Simulator version**: 1.18.2
- **Python version**: 3.10.12 

**Additional context**
N/A

**Comment by math411** [comment]
Hello @rchilaka-amzn, thank you for raising this issue. I shall have a look at this and work on a fix.

**Comment by speller26** [comment]
Should be fixed as of [v1.52.0](https://github.com/aws/amazon-braket-sdk-python/releases/tag/v1.52.0)

**Comment by christianbmadsen** [comment]
@krneta ro validate that this issue can be closed.

**Comment by krneta** [comment]
This is still an issue. 

The work around is to not use "angle", but to instead use "float". 

Supporting "angle" would require some work and would need to be added to our backlog. Adding Zia to determine the priority.

**Comment by speller26** [comment]
`angle` support fixed in the linked PR to the default simulator.

**Comment by speller26** [comment]
`angle` is supported as of [v1.53.1](https://github.com/aws/amazon-braket-default-simulator-python/releases/tag/v1.19.1)
